version: '2'
services:
  mysql:
    image: mysql:5.7.18
    environment:
      MYSQL_ROOT_PASSWORD: 'melody'
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
    ports:
      - '3306:3306'
    volumes:
      - ./var/mysql:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci

  rails:
    build: .
    image: lodge:develop
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: production
      DATABASE_URL: mysql2://root:melody@mysql:3306
      SECRET_KEY_BASE: __some_random_string__
      DEVISE_SECRET_KEY: __some_random_string__
      GOOGLE_CLIENT_ID: 
      GOOGLE_CLIENT_SECRET: 
      LODGE_DOMAIN: localhost:3000
      DELIVERY_METHOD: smtp
      MAIL_SENDER: example@example.com
      SMTP_ADDRESS: smtp.google.com
      SMTP_PORT: 587
      SMTP_USERNAME: username
      SMTP_PASSWORD: password
      SMTP_AUTH_METHOD: plain
      SMTP_ENABLE_STARTTLS_AUTO: 'true'
      SMTP_OPENSSL_VERIFY_MODE: none
      LODGE_THEME: lodge
      SYNTAX_HIGHLIGHT_THEME: pastie
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
    depends_on:
      - mysql
    volumes:
      - ./var/lodge:/usr/src/app/public/uploads
